#!/usr/bin/env bash
set_vars() {
  repo=$(echo $repo | sed -E 's/.+github.com.([^/]+\/[^/\.]+)(.git)?/\1/') # Get repos from URLs
  GLOBIGNORE="*"
  ENDPOINT="https://api.github.com/repos/$repo/stats/commit_activity"
  APPNAME="KyleMacey/repo-contrib-graph"
  ACCEPT_HEADER="Accept: application/vnd.github.full+json"
  DAYS[0]='S'
  DAYS[1]='M'
  DAYS[2]='T'
  DAYS[3]='W'
  DAYS[4]='T'
  DAYS[5]='F'
  DAYS[6]='S'
  if [ -n "$use_color" ]; then
    HEAT_1=$'\e[38;5;102m'
    HEAT_2=$'\e[38;5;46m'
    HEAT_3=$'\e[38;5;28m'
    HEAT_4=$'\e[38;5;22m'
    ENDC=$'\e[0m'
    COUNT_0_COMMITS="${HEAT_1}■${ENDC}"
    COUNT_1_5_COMMITS="${HEAT_2}■${ENDC}"
    COUNT_6_10_COMMITS="${HEAT_3}■${ENDC}"
    COUNT_11_PLUS_COMMITS="${HEAT_4}■${ENDC}"
  else
    COUNT_0_COMMITS='-'
    COUNT_1_5_COMMITS='+'
    COUNT_6_10_COMMITS='*'
    COUNT_11_PLUS_COMMITS='■'
  fi
  set_auth
}

check_dependencies()
{
  for dependency in curl jq; do
    type $dependency >/dev/null 2>&1 || { echo >&2 "You must install \"$dependency\" first. Aborting."; exit 1; }
  done
}

# Set our authorization token if it's provided
set_auth()
{
  if [ -n "$access_token" ]; then
    AUTH_STRING="Authorization: token $access_token"
  fi
}

# Since an uncached hit will kick off a task and return 202, we prime the
# ENDPOINT by hitting it until we get something other than 202
prime_endpoint()
{
  local res=202
  printf "Starting..."
  while [[ $res != 200 ]]; do
    res=$(curl -s -L -I ${AUTH_STRING:+-H "$AUTH_STRING"} -w %{http_code} $ENDPOINT | grep HTTP/1.1 | awk {'print $2'})
    printf "."
    sleep 1
    if [[ $res != 20? ]]; then
      echo ""
      echo "FATAL: Unable to retrieve repository data."
      echo "Server returned with status $res"
      exit 1
    fi
  done
  echo -e "\n"
}

print_headers()
{
  echo "$repo:"
}

print_key()
{
  printf '  %s: 0 commits     %s: 1-5 commits \n' $COUNT_0_COMMITS $COUNT_1_5_COMMITS
  printf '  %s: 6-10 commits  %s: 11+ commits \n' $COUNT_6_10_COMMITS $COUNT_11_PLUS_COMMITS
}

# Get our data from the API and massage it into a beautiful graph!
fetch_and_print()
{
  response_data=$(curl -s -L -G \
    -H "User-Agent: $APPNAME" \
    -H "$ACCEPT_HEADER" \
    ${AUTH_STRING:+-H "$AUTH_STRING"} \
    $ENDPOINT)

  if [ -n "$DEBUG" ]; then
    echo -e $response_data
    exit
  fi

  for d in $(seq 0 6); do
    printf "${DAYS[$d]} |"
    for w in $(seq 0 51); do
      local day=$(echo $response_data | jq ".[$w] | .days | .[$d]")
      local indicator=$COUNT_0_COMMITS

      if [ "$day" -ge 1 -a "$day" -le 5 ]; then indicator=$COUNT_1_5_COMMITS;
      elif [ "$day" -ge 6 -a "$day" -le 10 ]; then indicator=$COUNT_6_10_COMMITS;
      elif [ "$day" -ge 11 ]; then indicator=$COUNT_11_PLUS_COMMITS;
      fi

      printf '%s ' $indicator
    done
    echo ""
  done
}

# Do all the things!
generate_graph()
{
  set_vars
  check_dependencies
  prime_endpoint
  print_headers
  fetch_and_print
  print_key
}

usage() {
  echo "\
  usage: repo-contrib-graph [options]
          -r) repo: The repository you want to generate a contribution graph for
              format: username/repository
          -t) access_token: Your personal GitHub access token
          -c) color: display the graph with pretty colors!
          -h) usage: Display this help
          -d) debug: Dumps the JSON response and exits
  "
}

while getopts r:t:chd option; do
  case "${option}" in
  r)  repo=${OPTARG};;
  t)  access_token=${OPTARG};;
  c)  use_color=true;;
  h)  usage
      exit;;
  d)  DEBUG=true
  esac
done

if [ -z "$repo" ]; then
    usage
    exit
fi

generate_graph
